### ISSUE TITLE
Salesforce Object Merge

### ISSUE THREAD

**Issue by bryan-macfarlane** [kyleschmid/ObjectMerge#27]
Over the past several days we have attempted a number of contact merges using the Object Merge utility/app which have all failed in our Salesforce Sales environment

The process completes with an Error status with the Error Reason being "Error Running Query".

We are unsure why the recent merges are failing and looking for assistance as not sure if something has been introduced in our Salesforce environment.

[Object Merge Issue.pdf](https://github.com/kyleschmid/ObjectMerge/files/8881002/Object.Merge.Issue.pdf)

**Comment by kyleschmid** [comment]
@bryan-macfarlane This usually means one of the object/field API names is invalid. Try opening up the Developer Console, switching the Status to "Retry", and opening the debug log that gets generated. Scroll to the bottom and then start scrolling up from there. You should be able to find the true error Salesforce generated in the debug log. On a somewhat related note, it's been on my to-do list to add more error details to the Object Merge Pair record so you don't have to open up the debug log to see what the real issue is.
